export const AGUSAN_DEL_SUR_LOCATIONS: Record<string, string[]> = {
  'Bayugan City': ['Berseba', 'Bucac', 'Cagbas', 'Calaitan', 'Canayugan', 'Charito', 'Claro M. Recto', 'Del Carmen', 'Fili', 'Gamao', 'Getsemane', 'Grace Estate', 'Hamogaway', 'Ilaud', 'Magkiangkang', 'Mahayag', 'Mabuhay', 'Macopa', 'Magugpo', 'Maygatasan', 'Montevista', 'Mt. Ararat', 'Mt. Carmel', 'Mt. Olive', 'New Salem', 'Noli', 'Osmeña', 'Panaytay', 'Pinagalaan', 'Poblacion', 'Sagmone', 'Salvacion', 'San Agustin', 'San Isidro', 'San Juan', 'San Lorenzo', 'San Mateo', 'Santa Irene', 'Santa Teresita', 'Taglatawan', 'Tagubay', 'Verdu', 'Villa Undayon', 'Wawa'],
  'Bunawan': ['Bunawan Brook', 'Consuelo', 'Libertad', 'Mambalili', 'Mandacpan', 'Marcos', 'Nueva Era', 'Poblacion', 'San Andres', 'San Teodoro'],
  'Esperanza': ['Agbong', 'Aguinaldo', 'Balubo', 'Bentahon', 'Bunaguit', 'Catmonon', 'Cebantang', 'Concordia', 'Crossing Luna', 'Cubo', 'Dakutan', 'Duangan', 'Guadalupe', 'Hawilian', 'Kalabugao', 'Kinamaybay', 'Labao', 'Mac-Arthur', 'Mabuhay', 'Mahagcot', 'Maliwanag', 'Milagros', 'Nato', 'Oro', 'Piglawigan', 'Poblacion', 'Remedios', 'Salug', 'San Isidro', 'San Jose', 'San Toribio', 'San Vicente', 'Santa Ines', 'Segunda', 'Tagbalili', 'Tahina', 'Tandang Sora'],
  'La Paz': ['Angeles', 'Bataan', 'Comota', 'Halapitan', 'Langasian', 'Osmeña', 'Panagangan', 'Poblacion', 'Sagunto', 'San Patricio', 'Valentina', 'Villa Paz'],
  'Loreto': ['Binucayan', 'Bugdangan', 'Ferdinad', 'Johnson', 'Kasapa', 'Katipunan', 'Kauswagan', 'Magaud', 'Nueva Gracia', 'Poblacion', 'Sabud', 'San Isidro', 'San Mariano', 'San Vicente', 'Santa Teresa', 'Santo Niño', 'Waloe'],
  'Prosperidad': ['Aurora', 'Awa', 'Azpetia', 'Bausan', 'La Caridad', 'La Perian', 'La Purisima', 'La Suerte', 'La Union', 'Las Navas', 'Libertad', 'Los Arcos', 'Lucena', 'Mabuhay', 'Magsaysay', 'Mapaga', 'Napo', 'New Maug', 'Patin-ay', 'Poblacion (Bahbah)', 'Salimboga', 'San Chretien', 'San Joaquin', 'San Jose', 'San Lorenzo', 'San Martin', 'San Pedro', 'San Rafael', 'San Roque', 'San Vicente', 'Santa Irene', 'Santa Maria'],
  'Rosario': ['Bayugan', 'Cabantao', 'Cabawan', 'Libuac', 'Maligaya', 'Marfil', 'Novele', 'Poblacion', 'Santa Cruz', 'Tagbayagan', 'Wasian'],
  'San Francisco': ['Alegria', 'Bayugan 2', 'Bitan-agan', 'Borbon', 'Buenasuerte', 'Caimpugan', 'Das-agan', 'Ebro', 'Hubang', 'Karaos', 'Ladgadan', 'Lapinigan', 'Lucac', 'Mate', 'New Visayas', 'Ormaca', 'Pasta', 'Pisa-an', 'Poblacion', 'Rizal', 'San Isidro', 'San Juan', 'Santa Ana', 'Tagapua'],
  'San Luis': ['Anislagan', 'Balit', 'Baylo', 'Binicalan', 'Cecilia', 'Coalicion', 'Culi', 'Dimasalang', 'Don Alejandro', 'Don Pedro', 'Doña Flavia', 'Doña Maxima', 'Mahagsay', 'Muritula', 'Nuevo Trabajo', 'Poblacion', 'Policarpo', 'San Isidro', 'San Pedro', 'Santa Ines'],
  'Santa Josefa': ['Awao', 'Angas', 'Aurora', 'Concepcion', 'Pag-asa', 'Patrocinio', 'Poblacion', 'San Jose', 'Santa Isabel', 'Sayon', 'Tapaz'],
  'Sibagat': ['Afga', 'Anahawan', 'Banagbanag', 'Del Rosario', 'El Rio', 'Ilihan', 'Kauswagan', 'Kolambugan', 'Magkalape', 'Magsaysay', 'Mahayahay', 'New Tubigon', 'Padiay', 'Perez', 'Poblacion', 'San Isidro', 'San Vicente', 'Santa Cruz', 'Santa Maria', 'Sinai', 'Tabontabon', 'Tag-uyango', 'Villangit'],
  'Talacogon': ['Batucan', 'Buena Gracia', 'Causwagan', 'Culi', 'Del Monte', 'Desamparados', 'La Flora', 'Labnig', 'Maharlika', 'Marbon', 'Nabullian', 'Sabang Gibong', 'San Agustin', 'San Isidro', 'San Nicolas', 'Zamora'],
  'Trento': ['Basa', 'Cuevas', 'Kapatungan', 'Langkila-an', 'Manat', 'New Visayas', 'Pangyan', 'Poblacion', 'Pulang-lupa', 'Salvacion', 'San Ignacio', 'San Isidro', 'San Roque', 'Santa Maria', 'Tudela', 'Cebolin'],
  'Veruela': ['Anitap', 'Bacay II', 'Binongan', 'Del Monte', 'Don Mateo', 'Katipunan', 'La Fortuna', 'Limot', 'Magsaysay', 'Masayan', 'Poblacion', 'Sampaguita', 'San Gabriel', 'Santa Cruz', 'Santa Emilia', 'Sinobong']
};
